-- Lab objects for synthetic workload testing
-- Execute after terraform apply

CREATE DATABASE IF NOT EXISTS COST_COPILOT_DB;
USE DATABASE COST_COPILOT_DB;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS CORE;
CREATE SCHEMA IF NOT EXISTS MART;
CREATE SCHEMA IF NOT EXISTS OPS;
CREATE SCHEMA IF NOT EXISTS COST_COPILOT;

CREATE OR REPLACE STREAM RAW.EVENTS_LANDING_STREAM
  ON TABLE RAW.EVENTS_LANDING
  APPEND_ONLY = TRUE;

CREATE OR REPLACE PROCEDURE OPS.SP_PROCESS_EVENTS()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
  MERGE INTO CORE.FACT_EVENTS t
  USING (
    SELECT
      EVENT_ID,
      EVENT_TS,
      CUSTOMER_ID,
      PRODUCT_ID,
      QTY,
      UNIT_PRICE,
      (QTY * UNIT_PRICE)::NUMBER(16,2) AS EXTENDED_PRICE,
      CHANNEL,
      EVENT_TYPE
    FROM RAW.EVENTS_LANDING_STREAM
  ) s
  ON t.EVENT_ID = s.EVENT_ID
  WHEN MATCHED THEN UPDATE SET
    EVENT_TS = s.EVENT_TS,
    CUSTOMER_ID = s.CUSTOMER_ID,
    PRODUCT_ID = s.PRODUCT_ID,
    QTY = s.QTY,
    UNIT_PRICE = s.UNIT_PRICE,
    EXTENDED_PRICE = s.EXTENDED_PRICE,
    CHANNEL = s.CHANNEL,
    EVENT_TYPE = s.EVENT_TYPE,
    LOAD_TS = CURRENT_TIMESTAMP()
  WHEN NOT MATCHED THEN INSERT (
    EVENT_ID, EVENT_TS, CUSTOMER_ID, PRODUCT_ID, QTY, UNIT_PRICE, EXTENDED_PRICE, CHANNEL, EVENT_TYPE, LOAD_TS
  ) VALUES (
    s.EVENT_ID, s.EVENT_TS, s.CUSTOMER_ID, s.PRODUCT_ID, s.QTY, s.UNIT_PRICE, s.EXTENDED_PRICE, s.CHANNEL, s.EVENT_TYPE, CURRENT_TIMESTAMP()
  );

  INSERT OVERWRITE INTO MART.FACT_DAILY_REVENUE
  SELECT
    DATE_TRUNC('DAY', f.EVENT_TS)::DATE AS EVENT_DATE,
    f.CHANNEL,
    p.CATEGORY,
    SUM(f.EXTENDED_PRICE) AS REVENUE,
    COUNT(*) AS EVENT_COUNT,
    CURRENT_TIMESTAMP() AS REFRESH_TS
  FROM CORE.FACT_EVENTS f
  JOIN CORE.DIM_PRODUCT p ON f.PRODUCT_ID = p.PRODUCT_ID
  GROUP BY 1, 2, 3;

  RETURN 'OK';
END;
$$;

CREATE OR REPLACE TASK OPS.TASK_PROCESS_EVENTS
  WAREHOUSE = COST_COPILOT_LAB_WH
  SCHEDULE = '5 MINUTE'
AS
  CALL OPS.SP_PROCESS_EVENTS();

ALTER TASK OPS.TASK_PROCESS_EVENTS SUSPEND;

CREATE OR REPLACE VIEW MART.V_COMPLEX_MARGIN_ANALYSIS AS
WITH base AS (
  SELECT
    f.EVENT_TS::DATE AS EVENT_DATE,
    c.REGION,
    c.CUSTOMER_SEGMENT,
    p.CATEGORY,
    p.BRAND,
    f.CHANNEL,
    f.EXTENDED_PRICE AS REVENUE,
    (f.EXTENDED_PRICE * (0.35 + UNIFORM(0, 20, RANDOM()) / 100.0))::NUMBER(16,2) AS ESTIMATED_COST
  FROM CORE.FACT_EVENTS f
  JOIN CORE.DIM_CUSTOMER c ON c.CUSTOMER_ID = f.CUSTOMER_ID
  JOIN CORE.DIM_PRODUCT p ON p.PRODUCT_ID = f.PRODUCT_ID
),
agg AS (
  SELECT
    EVENT_DATE,
    REGION,
    CUSTOMER_SEGMENT,
    CATEGORY,
    BRAND,
    CHANNEL,
    SUM(REVENUE) AS REVENUE,
    SUM(ESTIMATED_COST) AS ESTIMATED_COST
  FROM base
  GROUP BY 1,2,3,4,5,6
)
SELECT
  *,
  (REVENUE - ESTIMATED_COST) AS EST_MARGIN,
  IFF(REVENUE = 0, 0, (REVENUE - ESTIMATED_COST) / REVENUE) AS MARGIN_PCT
FROM agg;
