-- Seed synthetic high-volume data (10M+ rows)

USE DATABASE COST_COPILOT_DB;
USE SCHEMA CORE;

ALTER SESSION SET QUERY_TAG = 'seed:dim_customer:run=bootstrap';
INSERT INTO CORE.DIM_CUSTOMER
SELECT
  SEQ4() + 1 AS CUSTOMER_ID,
  CASE
    WHEN UNIFORM(1, 100, RANDOM()) <= 15 THEN 'ENTERPRISE'
    WHEN UNIFORM(1, 100, RANDOM()) <= 50 THEN 'SMB'
    ELSE 'CONSUMER'
  END AS CUSTOMER_SEGMENT,
  ARRAY_CONSTRUCT('NA','EMEA','APAC','LATAM')[UNIFORM(0,4,RANDOM())]::STRING AS REGION,
  DATEADD('DAY', -UNIFORM(1, 3650, RANDOM()), CURRENT_TIMESTAMP()) AS CREATED_AT
FROM TABLE(GENERATOR(ROWCOUNT => 1000000));

ALTER SESSION SET QUERY_TAG = 'seed:dim_product:run=bootstrap';
INSERT INTO CORE.DIM_PRODUCT
SELECT
  SEQ4() + 1 AS PRODUCT_ID,
  ARRAY_CONSTRUCT('FLIGHT','HOTEL','CAR','PACKAGE','UPSELL')[UNIFORM(0,5,RANDOM())]::STRING AS CATEGORY,
  'BRAND_' || (UNIFORM(1, 200, RANDOM()))::STRING AS BRAND,
  (UNIFORM(500, 250000, RANDOM()) / 100.0)::NUMBER(12,2) AS LIST_PRICE
FROM TABLE(GENERATOR(ROWCOUNT => 200000));

USE SCHEMA RAW;
ALTER SESSION SET QUERY_TAG = 'seed:events_landing:run=bootstrap';
INSERT INTO RAW.EVENTS_LANDING
SELECT
  SEQ4() + 1 AS EVENT_ID,
  DATEADD('SECOND', -UNIFORM(1, 1209600, RANDOM()), CURRENT_TIMESTAMP()) AS EVENT_TS,
  UNIFORM(1, 1000000, RANDOM()) AS CUSTOMER_ID,
  UNIFORM(1, 200000, RANDOM()) AS PRODUCT_ID,
  UNIFORM(1, 8, RANDOM()) AS QTY,
  (UNIFORM(300, 150000, RANDOM()) / 100.0)::NUMBER(12,2) AS UNIT_PRICE,
  ARRAY_CONSTRUCT('web','mobile','api','partner')[UNIFORM(0,4,RANDOM())]::STRING AS CHANNEL,
  ARRAY_CONSTRUCT('booked','modified','cancelled','refunded')[UNIFORM(0,4,RANDOM())]::STRING AS EVENT_TYPE,
  OBJECT_CONSTRUCT('session_id', UUID_STRING(), 'campaign_id', UNIFORM(1, 500, RANDOM())) AS PAYLOAD
FROM TABLE(GENERATOR(ROWCOUNT => 12000000));

USE SCHEMA OPS;
ALTER SESSION SET QUERY_TAG = 'seed:procedure:run=bootstrap';
CALL OPS.SP_PROCESS_EVENTS();
