-- Execute representative heavy workloads with tags for copilot detection

USE DATABASE COST_COPILOT_DB;
USE WAREHOUSE COST_COPILOT_LAB_WH;

ALTER SESSION SET QUERY_TAG = 'airflow:dev:dag=cost_burst:task=expensive_rollup:run=manual_1';
WITH daily AS (
  SELECT
    f.EVENT_TS::DATE AS EVENT_DATE,
    c.REGION,
    c.CUSTOMER_SEGMENT,
    p.CATEGORY,
    p.BRAND,
    SUM(f.EXTENDED_PRICE) AS REVENUE,
    COUNT(*) AS EVENTS
  FROM CORE.FACT_EVENTS f
  JOIN CORE.DIM_CUSTOMER c ON c.CUSTOMER_ID = f.CUSTOMER_ID
  JOIN CORE.DIM_PRODUCT p ON p.PRODUCT_ID = f.PRODUCT_ID
  WHERE f.EVENT_TS >= DATEADD('DAY', -30, CURRENT_TIMESTAMP())
  GROUP BY 1,2,3,4,5
),
ranked AS (
  SELECT
    *,
    DENSE_RANK() OVER (PARTITION BY EVENT_DATE, REGION ORDER BY REVENUE DESC) AS RK
  FROM daily
)
SELECT *
FROM ranked
WHERE RK <= 10
ORDER BY EVENT_DATE DESC, REGION, REVENUE DESC;

ALTER SESSION SET QUERY_TAG = 'dbt:dev:model=fct_margin_deep:run=manual_1';
SELECT
  a.EVENT_DATE,
  a.REGION,
  a.CUSTOMER_SEGMENT,
  a.CATEGORY,
  a.BRAND,
  a.CHANNEL,
  a.REVENUE,
  a.ESTIMATED_COST,
  a.EST_MARGIN,
  a.MARGIN_PCT,
  b.REVENUE AS REV_PREV_DAY,
  (a.REVENUE - COALESCE(b.REVENUE, 0)) AS REV_DELTA
FROM MART.V_COMPLEX_MARGIN_ANALYSIS a
LEFT JOIN MART.V_COMPLEX_MARGIN_ANALYSIS b
  ON b.EVENT_DATE = DATEADD('DAY', -1, a.EVENT_DATE)
 AND b.REGION = a.REGION
 AND b.CUSTOMER_SEGMENT = a.CUSTOMER_SEGMENT
 AND b.CATEGORY = a.CATEGORY
 AND b.BRAND = a.BRAND
 AND b.CHANNEL = a.CHANNEL
QUALIFY ROW_NUMBER() OVER (
  PARTITION BY a.EVENT_DATE, a.REGION, a.CUSTOMER_SEGMENT
  ORDER BY ABS(a.REVENUE - COALESCE(b.REVENUE, 0)) DESC
) <= 50;

ALTER SESSION SET QUERY_TAG = 'snowpark:dev:job=stream_backfill:run=manual_1';
INSERT INTO RAW.EVENTS_LANDING
SELECT
  900000000 + SEQ4() + 1 AS EVENT_ID,
  DATEADD('SECOND', -UNIFORM(1, 7200, RANDOM()), CURRENT_TIMESTAMP()) AS EVENT_TS,
  UNIFORM(1, 1000000, RANDOM()) AS CUSTOMER_ID,
  UNIFORM(1, 200000, RANDOM()) AS PRODUCT_ID,
  UNIFORM(1, 8, RANDOM()) AS QTY,
  (UNIFORM(300, 150000, RANDOM()) / 100.0)::NUMBER(12,2) AS UNIT_PRICE,
  ARRAY_CONSTRUCT('web','mobile','api','partner')[UNIFORM(0,4,RANDOM())]::STRING AS CHANNEL,
  ARRAY_CONSTRUCT('booked','modified','cancelled','refunded')[UNIFORM(0,4,RANDOM())]::STRING AS EVENT_TYPE,
  OBJECT_CONSTRUCT('session_id', UUID_STRING(), 'campaign_id', UNIFORM(1, 500, RANDOM())) AS PAYLOAD
FROM TABLE(GENERATOR(ROWCOUNT => 250000));

ALTER SESSION SET QUERY_TAG = 'airflow:dev:dag=cost_burst:task=process_stream:run=manual_1';
CALL OPS.SP_PROCESS_EVENTS();
